version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: uci
      WORDPRESS_DB_PASSWORD: uci_pw
      WORDPRESS_DB_NAME: uci_db
    volumes:
      - ./src/wp-content:/var/www/html/wp-content

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: uci_db
      MYSQL_USER: uci
      MYSQL_PASSWORD: uci_pw
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql